spring:
  application:
    name: faq-chat-bot
  http:
    converters:
      preferred-json-mapper: gson

# Nonce encryption
nonce:
  encryption:
    key: ${NONCE_ENCRYPTION_KEY:<NONCE-ENCRYPTION-KEY>}

openai:
  api:
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
    key:  ${OPENAI_API_KEY:<YOUR-KEY>}
  model: gpt-4o-mini

logging:
  level:
    root: INFO
    com.bng: INFO  # Your package name
  file:
    name: logs/qa-log.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: ${JWT_SECRET:<JWT-SECRET>}  # Secret key for JWT signing
  expiration:  ${JWT_EXPIRATION:300000}  # 5 minutes in milliseconds